# Generated by Django 5.1.6 on 2025-02-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_name', models.CharField(max_length=255)),
                ('cert_holder_name', models.CharField(max_length=255)),
                ('cert_holder_address', models.CharField(max_length=255)),
                ('cert_holder_city', models.CharField(max_length=100)),
                ('cert_holder_state', models.CharField(max_length=2)),
                ('cert_holder_zip', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('general_liability', models.BooleanField(default=False)),
                ('auto_liability', models.BooleanField(default=False)),
                ('work_comp', models.BooleanField(default=False)),
                ('umbrella', models.BooleanField(default=False)),
                ('ai_general_liability', models.BooleanField(default=False)),
                ('ai_auto_liability', models.BooleanField(default=False)),
                ('primary_general_liability', models.BooleanField(default=False)),
                ('waiver_general_liability', models.BooleanField(default=False)),
                ('job_location', models.CharField(max_length=255)),
            ],
        ),
    ]
