# Generated by Django 5.1.6 on 2025-03-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insured_name', models.CharField(max_length=255)),
                ('cert_holder_name', models.CharField(max_length=255)),
                ('cert_holder_address', models.CharField(max_length=255)),
                ('cert_holder_city', models.CharField(max_length=100)),
                ('cert_holder_state', models.CharField(max_length=2)),
                ('cert_holder_zip', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('general_liability', models.BooleanField(default=False)),
                ('auto_liability', models.BooleanField(default=False)),
                ('work_comp', models.BooleanField(default=False)),
                ('umbrella', models.BooleanField(default=False)),
                ('ai_general_liability', models.BooleanField(default=False)),
                ('ai_auto_liability', models.BooleanField(default=False)),
                ('primary_general_liability', models.BooleanField(default=False)),
                ('waiver_general_liability', models.BooleanField(default=False)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_holder_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_holder_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_holder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lines_business_excess', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_cancellation', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_line', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_matt', models.EmailField(blank=True, max_length=254, null=True)),
                ('cc_insured', models.BooleanField(default=False)),
                ('form_number_gl_ongoing', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_gl_complete', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_primary_gl', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_primary_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_waiver_gl', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_waiver_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('form_number_waiver_work_comp', models.CharField(blank=True, max_length=255, null=True)),
                ('umbrella_coi', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_cancellation_value1', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_cancellation_value2', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_complete_operations', models.BooleanField(default=False)),
                ('primary_auto_liability', models.BooleanField(default=False)),
                ('waiver_auto_liability', models.BooleanField(default=False)),
                ('waiver_work_comp', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
